#!/bin/bash
# Apply blue and green deployments
kubectl apply -f messaging_app/blue_deployment.yaml
kubectl apply -f messaging_app/green_deployment.yaml

# Apply service
kubectl apply -f messaging_app/kubeservice.yaml

# Check logs of green deployment pods
GREEN_PODS=$(kubectl get pods -l app=django-app-green -o jsonpath="{.items[*].metadata.name}")
for pod in $GREEN_PODS; do
    kubectl logs $pod
done
